### ISSUE TITLE
About patches

### ISSUE THREAD

**Issue by AERDU** [chadcat7/best#1]
Which patch is "ResizeText" from? I'd like to apply it to my own build but am not quite sure where you got the .diff from.

**Comment by AERDU** [comment]
nevermind, found an [old commit](https://github.com/chadcat7/best/commit/f4c8c759c0f53d6b218ca564fa333bce4abccd9e#diff-048db8ba01f6b01a9f44229274ba3c49644353f6f52af3942bb100de1117dce3) that supplies it, not tested if it patches however.

**Comment by namishh** [comment]
aahh okay i am sorry i was busy with my exams , I forgot about this issue.
